### ISSUE TITLE
Option to disable source maps

### ISSUE THREAD

**Issue by francislavoie** [TylorS/snowpack-plugin-hash#8]
See https://github.com/TylorS/snowpack-plugin-hash/issues/6#issuecomment-762466950

> Noticed that it outputs source map files, but I don't use source map files otherwise because I don't minify my code. Could we add an option for that?

**Comment by TylorS** [comment]
Hey @francislavoie I'm happy to hear there are outputs now 😀 

This should be simple enough, there's already some built-in support for having or not having sourceMaps.

**Comment by TylorS** [comment]
Hey @francislavoie, just re-reading your original comment and wanna make sure the functionality of the library is clear, since I know it might very well not be 😄 

> I don't use source map files otherwise because I don't minify my code

The sourceMaps that are generated would then just be with the hash additions, it should help keep any errors on the correct line numbers & columns. If you _were_ producing other sourceMaps, it would perform a remapping of the sourceMaps to continue to be accurate.

Either way, I went ahead and added an option for this because it is practically built-in already. With `v0.12.0` you should be able to configure `sourceMaps: false` or piggyback on snowpack's `buildOptions.sourcemap: false`

**Comment by francislavoie** [comment]
Yep, I think I understood that.

Thanks for the change!

FWIW I only realized while in the shower yesterday thinking about it that hashing problem has a harder solution than I thought originally, since the import tree needs to be determined so that they are hashed in the correct order. I was thinking originally it could just be a simple transformation of each file without tracing the imports.

**Comment by TylorS** [comment]
@francislavoie Yeah.. when I had that realization I opened #3 and started working on making this a "real" thing (with @typed/content-hash). The original algorithm I had before was a lot faster since it didn't have to go 1-by-1 through the topologically sorted documents, but yeah it's the only way to ensure the hashes really mean something and provide the correct cache busts.

**Comment by francislavoie** [comment]
Just tried out the latest, and source maps are no longer output (didn't need to change my config). Thanks!

Btw, FWIW, I'm still not sure if I'll end up using this plugin, because I don't really want to move to a workflow that involves running a full `snowpack build` (without `--watch`). I'm trying to make this have clean DX (developer experience), cause asking everyone who will work on this project to run a full build before committing is error prone and slow :frowning_face:

**Comment by TylorS** [comment]
Glad to hear it is working well enough for you for now 👍 

I hear you about possibly not using it in the end. I might open some issues/discussions in snowpack to see about what kinds of plugin API might be available for this kind of thing or if it is totally out of scope. The only interim solution I can think of right now is to add watch support directly to `@typed/content-hash` and allow it to watch a build directory, and then output a separate hashed build directory. I'll likely do this either way just so that I @typed/content-hash is a standalone library for that functionality

**Comment by francislavoie** [comment]
Sounds good! Feel free to @ me when you have that working, I'll give it a shot.
